### ISSUE TITLE
Document support for Node V8 (and any known issues) 

### ISSUE THREAD

**Issue by armstro** [zowe/zlux-server-framework#120]
Node V8 has been announced by IBM - Zowe needs to document what support position is. 

FYI - 
https://www.ibm.com/us-en/marketplace/sdk-nodejs-compiler-zos
https://www.ibm.com/us-en/marketplace/sdk-nodejs-compiler-zos/details

**Comment by armstro** [comment]
For awareness Node V6 end of marketing and support announced 
End of marketing means no more downloads of V6 (Sept 2, 2019) and end of support Sept 30, 2020 

https://user-images.githubusercontent.com/37591195/60896666-baf30a80-a234-11e9-8578-98adebe7ddfb.png

**Comment by 1000TurquoisePogs** [comment]
Looks like the docs now reflect that this is supported.
