### ISSUE TITLE
MVD fails to start on ZD&T system

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux-server-framework#193]
I installed PTF 1.10.0 on a ZD&T system.  When I started ZWESVSTC, only 12 of the expected 18 STCs came up.  The missing ones were related to node.js.  I saw this error in STDOUT
```
<ZWED:16843687> ZWESVUSR CRITICAL (_zsf.cluster,native array.js:958) ZWED0115E - Unable to retrieve storage object from cluster. This is ...
You may change the default of '5000' ms by setting 'node.cluster.storageTimeout' within the config. Timeout call null/clusterManager/getStorageAll
```
Another symptom is that the MVD is not available.  This is because the zssServer has not started, as shown by the fact that this message is missing from the STDOUT:
```
zssServer startup, version 1.10.0+20200403
```

To fix this, I changed
```
zowe/zlux-server-framework /lib/clusterManager.js 
```
I increased the timeout (specified in milliseconds) from 5 seconds 
```
var storageTimeout = 5000; 
```
to 60 seconds.

**Comment by John-A-Davies** [comment]
@1000TurquoisePogs Please assign this to the right person.

**Comment by stevenhorsman** [comment]
What's the difference between this and #195 ?

**Comment by John-A-Davies** [comment]
Only that this one is a runtime fault, due to the low value of storageTimeout , whereas #195 requires storageTimeout to be configurable outside the read-only runtime directory.

**Comment by stevenhorsman** [comment]
So they are both resolved by the same thing?
