### ISSUE TITLE
Externalise timeout

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux-server-framework#195]
As seen in issue #193 , it's useful to have such values externalised into a .ENV file or similar.

**Comment by John-A-Davies** [comment]
@1000TurquoisePogs can you make this a suggestion, please?  I've limited powers in this repo.

**Comment by stevenhorsman** [comment]
From a slack post Sean suggested: "edit $INSTANCE_DIR/instance.env to add ZWED_node_cluster_storageTimeout=30000 or some other number. It shouldn't effect performance."

**Comment by stevenhorsman** [comment]
Created https://github.com/zowe/docs-site/issues/1164 for this issue
